/**:
  ros__parameters:
    robot_description_kinematics:
      arm_0:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3

      arm_1:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3

# /**:
#   ros__parameters:
#     robot_description_kinematics:
#       arm_0:
#         kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#         kinematics_solver_search_resolution: 0.005
#         kinematics_solver_timeout: 0.05
#         kinematics_solver_attempts: 3