# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_0_controller
    - arm_1_controller

  arm_0_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_0_shoulder_pan_joint
      - arm_0_shoulder_lift_joint
      - arm_0_elbow_joint
      - arm_0_wrist_1_joint
      - arm_0_wrist_2_joint
      - arm_0_wrist_3_joint
  arm_1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_shoulder_pan_joint
      - arm_1_shoulder_lift_joint
      - arm_1_elbow_joint
      - arm_1_wrist_1_joint
      - arm_1_wrist_2_joint
      - arm_1_wrist_3_joint